version: '3'

services:
  mongodb:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
      - ./dataBase/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    restart: always

  product-service:
    build: ./product
    volumes:
      - ./product:/usr/src/app
    ports:
      - 5001:80
    restart: always

  website:
    image: php:apache
    volumes:
      - ./website:/var/www/html
    ports:
      - 5002:80
    depends_on:
      - product-service
    restart: always

volumes:
  mongodb_data: